CREATE TABLE ESTATE_AGENT (
  EID CHAR(3) CONSTRAINT EID_LENGTH CHECK (LENGTHB(EID) = 3),
  ENAME VARCHAR(25),
  HQ VARCHAR(25),
  EADDRESS VARCHAR(55),
  WEBSITE VARCHAR(40),
  ECONTACT CHAR(12),
  CONSTRAINT PKEY_ESTATE_AGENT PRIMARY KEY (EID)
);

CREATE TABLE STAFF (
  SID CHAR(4) CONSTRAINT SID_LENGTH CHECK (LENGTHB(SID) = 4),
  SNAME VARCHAR(25),
  SADDRESS VARCHAR(55),
  SCONTACT CHAR(12),
  SDETAILS CHAR(1) CONSTRAINT SDETAILS CHECK (SDETAILS IN ('M', 'F', 'O')),
  CONSTRAINT PKEY_STAFF PRIMARY KEY (SID)
);

CREATE TABLE BRANCH (
  BCODE CHAR(4) CONSTRAINT BCODE_LENGTH CHECK (LENGTHB(BCODE) = 4),
  BADDRESS VARCHAR(55),
  BCONTACT CHAR(12),
  MANAGER CHAR(4) CONSTRAINT UNIQ_MANAGER UNIQUE,
  CONSTRAINT PKEY_BRANCH PRIMARY KEY (BCODE)
);

CREATE TABLE OFFICES (
  ESTATE CHAR(3),
  BRANCH CHAR(4),
  CONSTRAINT PKEY_OFFICES PRIMARY KEY (ESTATE, BRANCH)
);

CREATE TABLE EMPLOYMENT (
  BRANCH CHAR(4),
  STAFF CHAR(4),
  CONSTRAINT PKEY_EMPLOYMENT PRIMARY KEY (BRANCH, STAFF)
);

CREATE TABLE CUSTOMER (
  CCODE CHAR(3) CONSTRAINT CCODE CHECK (LENGTHB(CCODE) = 3),
  CNAME VARCHAR(25),
  CADDRESS VARCHAR(55),
  CBIRTH DATE CONSTRAINT OF_LEGAL_AGE CHECK (CBIRTH <= '01-JAN-2004'),
  CGENDER CHAR(1) CONSTRAINT CGENDER CHECK (CGENDER IN ('M', 'F', 'O')),
  CCONTACT CHAR(12),
  CONSTRAINT PKEY_CUSTOMER PRIMARY KEY (CCODE)
);

CREATE TABLE PROPERTY (
  PID CHAR(4) CONSTRAINT PID_LENGTH CHECK (LENGTHB(PID) = 4),
  DATE_REGISTERED DATE,
  LANDLORD CHAR(3),
  PADDRESS VARCHAR(55),
  PLOCATION VARCHAR(25),
  PDESCRIPTION VARCHAR(10) CONSTRAINT PDESCRIPTION CHECK (PDESCRIPTION IN ('Apartment', 'Commercial', 'Condo', 'Duplex', 'House')),
  PDETAILS VARCHAR(200),
  PASKING_PRICE NUMBER(8),
  PTYPE VARCHAR(13) CONSTRAINT PTYPE CHECK (PTYPE IN ('Attached', 'Semi-detached', 'Detached', 'Zero Lot Line', 'Terrace')),
  NO_ROOMS VARCHAR(2),
  AVAILABILITY DATE CONSTRAINT AVAILABLE_NOT_BEFORE_REGISTRATION CHECK (AVAILABILITY >= DATE_REGISTERED),
  CONTRACT_TYPE CHAR(4) CONSTRAINT CONTRACT_TYPE CHECK (CONTRACT_TYPE IN ('Rent', 'Sale')),
  CONSTRAINT PKEY_PROPERTY PRIMARY KEY (PID)
);

CREATE TABLE MANAGED_P (
  BRANCH CHAR(4),
  PROPERTY CHAR(4),
  CONSTRAINT PKEY_MANAGEDP PRIMARY KEY (BRANCH, PROPERTY)
);

CREATE TABLE VIEWING (
  VID CHAR(4) CONSTRAINT VID_LENGTH CHECK (LENGTHB(VID) = 4),
  CUSTOMER CHAR(3),
  PROPERTY CHAR(4),
  DATE_TIME TIMESTAMP,
  VCOMMENTS VARCHAR(150),
  CONSTRAINT PKEY_VIEWING PRIMARY KEY (VID)
);

CREATE TABLE SOLD (
  SOLD_PROPERTY CHAR(4),
  SOLD_TO CHAR(3),
  SELLING_PRICE NUMBER(8),
  STAMP_DUTY NUMBER(6),
  SCOMMISSION NUMBER(6) CONSTRAINT SCOMMISSION_FROM_PRICE CHECK (SCOMMISSION <= SELLING_PRICE * 0.1),
  OFF_MARKET DATE,
  CONSTRAINT PKEY_SOLD PRIMARY KEY (SOLD_PROPERTY, SOLD_TO)
);

CREATE TABLE RENTED (
  RENTED_PROPERTY CHAR(4),
  RRENT NUMBER(6),
  RDEPOSIT NUMBER(6) CONSTRAINT RDEPOSIT_TOTAL CHECK (RDEPOSIT = RRENT * 3),
  RCOMMISSION NUMBER(6) CONSTRAINT RCOMMISION_FROM_RENT CHECK (RCOMMISSION <= RRENT),
  TENANT CHAR(3),
  CONTRACT_DATE DATE,
  CONSTRAINT PKEY_RENTED PRIMARY KEY (RENTED_PROPERTY)
);

CREATE TABLE RENT_CONTRACT (
  RENTED_PROPERTY CHAR(4),
  TENANT CHAR(3),
  RSTART_DATE DATE,
  REND_DATE DATE CONSTRAINT END_NOT_BEFORE_START CHECK (REND_DATE >= RSTART_DATE),
  DEPOSIT_PROTECTION VARCHAR(10),
  CONSTRAINT PKEY_RENT_CONTRACT PRIMARY KEY (RENTED_PROPERTY, TENANT)
);
